%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.6 and Fixed-Point Designer 6.3           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [s_rc,S_range_c] = Distance_Plus_Compress_wrapper_fixpt(s_echo,Nr,Naz,Nrg,Fr,Kr)
    fm = get_fimath();
    s_echo_in = fi( s_echo, 1, 14, 12, fm );
    Nr_in = fi( Nr, 0, 8, 0, fm );
    Naz_in = fi( Naz, 0, 9, 0, fm );
    Nrg_in = fi( Nrg, 0, 9, 0, fm );
    Fr_in = fi( Fr, 0, 26, 0, fm );
    Kr_in = fi( Kr, 0, 45, 0, fm );
    [s_rc_out,S_range_c_out] = Distance_Plus_Compress_fixpt( s_echo_in, Nr_in, Naz_in, Nrg_in, Fr_in, Kr_in );
    s_rc = double( s_rc_out );
    S_range_c = double( S_range_c_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
