# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/WYHAIRCAS/Desktop/plus_compress/FIR_TEST/FIR_TEST.srcs/sources_1/ip/fir_h_i/fir_h_i.xci
# IP: The module: 'fir_h_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/FIR_TEST/FIR_TEST.srcs/sources_1/ip/fir_h_i/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_h_i'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/FIR_TEST/FIR_TEST.srcs/sources_1/ip/fir_h_i/fir_h_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_h_i'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/WYHAIRCAS/Desktop/plus_compress/FIR_TEST/FIR_TEST.srcs/sources_1/ip/fir_h_i/fir_h_i.xci
# IP: The module: 'fir_h_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/FIR_TEST/FIR_TEST.srcs/sources_1/ip/fir_h_i/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_h_i'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/FIR_TEST/FIR_TEST.srcs/sources_1/ip/fir_h_i/fir_h_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_h_i'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
