# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ROM_320x16_S_I/ROM_320x16_S_I.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_320x16_S_I || ORIG_REF_NAME==ROM_320x16_S_I} -quiet] -quiet

# IP: ip/Conv_Sq_Hq/Conv_Sq_Hq.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Conv_Sq_Hq || ORIG_REF_NAME==Conv_Sq_Hq} -quiet] -quiet

# IP: ip/Conv_Sq_Hi/Conv_Sq_Hi.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Conv_Sq_Hi || ORIG_REF_NAME==Conv_Sq_Hi} -quiet] -quiet

# IP: ip/Conv_Si_Hq/Conv_Si_Hq.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Conv_Si_Hq || ORIG_REF_NAME==Conv_Si_Hq} -quiet] -quiet

# IP: ip/Conv_Si_Hi/Conv_Si_Hi.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Conv_Si_Hi || ORIG_REF_NAME==Conv_Si_Hi} -quiet] -quiet
