# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Conv_Sq_Hq/Conv_Sq_Hq.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Conv_Sq_Hq || ORIG_REF_NAME==Conv_Sq_Hq} -quiet] -quiet

# IP: ip/Conv_Sq_Hi/Conv_Sq_Hi.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Conv_Sq_Hi || ORIG_REF_NAME==Conv_Sq_Hi} -quiet] -quiet
