# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/ROM_320x16_S_I/ROM_320x16_S_I.xci
# IP: The module: 'ROM_320x16_S_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/ROM_320x16_S_I/ROM_320x16_S_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_320x16_S_I'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/ROM_320x16_S_I/ROM_320x16_S_I.xci
# IP: The module: 'ROM_320x16_S_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/ROM_320x16_S_I/ROM_320x16_S_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_320x16_S_I'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
