# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ROM_320x32_S_I_1/ROM_320x32_S_I.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_320x32_S_I || ORIG_REF_NAME==ROM_320x32_S_I} -quiet] -quiet
