# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/Conv_Si_Hq/Conv_Si_Hq.xci
# IP: The module: 'Conv_Si_Hq' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/Conv_Si_Hq/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv_Si_Hq'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/Conv_Si_Hq/Conv_Si_Hq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv_Si_Hq'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/Conv_Si_Hq/Conv_Si_Hq.xci
# IP: The module: 'Conv_Si_Hq' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/Conv_Si_Hq/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv_Si_Hq'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/WYHAIRCAS/Desktop/plus_compress/Plus_Compress_Wave_Out/Plus_Compress_Wave_Out.srcs/sources_1/ip/Conv_Si_Hq/Conv_Si_Hq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv_Si_Hq'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
